/// <reference types="node" />
/* eslint-disable no-console */
/**
 * Builds recovery/sql/03-config-replay.sql — Stage 2.3: configuration that
 * reached production outside the seed scripts and does not replay on a fresh
 * database. Statements are COPIED VERBATIM from the migration files, never
 * retyped, so the replay cannot drift from what production ran.
 *
 * No database access. Writes one file.
 *
 *   npx tsx recovery/scripts/build-03-config-replay.ts
 *
 * Included (the seeds lack these — verified 2026-09-14):
 *   - manual-migrations/002_iip_to_manual.sql          IIP → manual
 *   - D2b                                              India CPI → manual
 *   - 20260629120000 recalibrate IND13 v2 bands        (seed already matches; idempotent)
 *   - 20260702120100 fix IND07 formula                 seed-rules-v2 still has abs(fii_net)
 *   - 20260817130000 IND13 v3 percentile_rank          expires v2 at 2026-08-16
 *   - 20260817150000 IND10/11/12 v3 rolling_slope_sigma expires v2 at 2026-08-16
 *   - 20260817160000 NSE holidays (INSERT only)        ON CONFLICT DO NOTHING
 *
 * Excluded (already in the seeds, or no-ops on a fresh database):
 *   - 20260608120100 / 20260610130100 / 20260713120000 price-source switches — seed.ts carries
 *     the final eodhd/yahoo sources
 *   - 20260702120000 IND14 indicator — seed.ts carries it
 *   - 20260731120000 pair template currencies / asset map — seed-edgefinder.ts seeds both
 *   - manual-sql/edgefinder_step_b + phase_3c — net effect (Non-Commercials) is in the seed
 *   - manual-sql/edgefinder_phase_3b1_ppi_rename — seed uses the *_MOM codes
 *   - manual-sql/edgefinder_phase_3b15 — no jblanked sources exist in the seed
 *   - manual-sql/edgefinder_phase_3b1_cleanup — deletes rows that will never exist
 *   - data backfills 20260817120000/140000/170000/190000 — rows do not exist yet
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(__dirname, '..', '..');
const MIG = join(ROOT, 'prisma', 'migrations');
const read = (...p: string[]) => readFileSync(join(...p), 'utf8').replace(/\r\n/g, '\n').trim();
const mig = (dir: string) => read(MIG, dir, 'migration.sql');

function nseHolidayInsertOnly(): string {
  const sql = mig('20260817160000_nse_holiday_calendar');
  const at = sql.indexOf('INSERT INTO "nse_holidays"');
  if (at < 0) throw new Error('nse_holidays INSERT not found');
  const body = sql.slice(at);
  if (!/ON CONFLICT \("date"\) DO NOTHING;\s*$/.test(body)) {
    throw new Error('nse_holidays INSERT does not end with ON CONFLICT ("date") DO NOTHING;');
  }
  return body;
}

const parts: Array<[string, string]> = [
  ['manual-migrations/002_iip_to_manual.sql', read(ROOT, 'prisma', 'manual-migrations', '002_iip_to_manual.sql')],
  [
    'D2b (confirmed by the user 2026-09-13): India CPI is hand-filled; seed.ts says fred',
    `UPDATE indicators\nSET data_source = 'manual',\n    updated_at = NOW()\nWHERE code = 'IND_NIFTY_03_CPI';`,
  ],
  ['20260629120000_recalibrate_nifty_ind13_fii_ls_bands', mig('20260629120000_recalibrate_nifty_ind13_fii_ls_bands')],
  ['20260702120100_fix_nifty_ind7_dii_absorption_net_formula', mig('20260702120100_fix_nifty_ind7_dii_absorption_net_formula')],
  ['20260817130000_nifty_ind13_percentile_rank_v3', mig('20260817130000_nifty_ind13_percentile_rank_v3')],
  ['20260817150000_nifty_ind10_11_12_slope_sigma_v3', mig('20260817150000_nifty_ind10_11_12_slope_sigma_v3')],
  ['20260817160000_nse_holiday_calendar (INSERT only; the table is built by db push)', nseHolidayInsertOnly()],
];

for (const [label, sql] of parts) {
  if (/\b(BEGIN|COMMIT|ROLLBACK)\s*;/i.test(sql)) throw new Error(`${label} carries its own transaction control`);
  if (/\b(DROP|TRUNCATE|DELETE\s+FROM)\b/i.test(sql.replace(/--[^\n]*/g, ''))) {
    throw new Error(`${label} contains a destructive statement — refusing to include it`);
  }
}

const header = `-- =============================================================================
-- Lucid recovery — Stage 2.3: configuration replay.
-- GENERATED by recovery/scripts/build-03-config-replay.ts on ${new Date().toISOString()}.
-- Do not edit by hand — edit the generator and rebuild.
--
-- Run AFTER all seed scripts (seed.ts, seed-rules-v2.ts, seed-edgefinder.ts,
-- seed-indicator-variants.ts, seed-compass-config.ts). One transaction.
-- Every statement is idempotent: UPDATEs by code/version, INSERTs with
-- ON CONFLICT DO NOTHING. See the generator for what was excluded and why.
-- =============================================================================
`;

const out = [header, 'BEGIN;', ...parts.map(([label, sql]) => `\n-- ── ${label} ${'─'.repeat(Math.max(0, 70 - label.length))}\n${sql}`), '\nCOMMIT;\n'].join('\n');
const file = join(ROOT, 'recovery', 'sql', '03-config-replay.sql');
writeFileSync(file, out);
console.log(`wrote ${file}`);
console.log(`sections: ${parts.length}   lines: ${out.split('\n').length}   holiday rows: ${(out.match(/^\('20\d\d-/gm) ?? []).length}`);
