-- =============================================================================
-- Lucid recovery — Stage 2.3: configuration replay.
-- GENERATED by recovery/scripts/build-03-config-replay.ts on 2026-09-13T19:55:30.176Z.
-- Do not edit by hand — edit the generator and rebuild.
--
-- Run AFTER all seed scripts (seed.ts, seed-rules-v2.ts, seed-edgefinder.ts,
-- seed-indicator-variants.ts, seed-compass-config.ts). One transaction.
-- Every statement is idempotent: UPDATEs by code/version, INSERTs with
-- ON CONFLICT DO NOTHING. See the generator for what was excluded and why.
-- =============================================================================

BEGIN;

-- ── manual-migrations/002_iip_to_manual.sql ───────────────────────────────
-- =========================================================
-- Manual SQL Migration: IIP data source change
-- Apply AFTER prisma migrate creates the cleanup migration.
-- =========================================================
-- FRED's INDPROINDMISMEI series stopped updating in Jan 2023.
-- Moving IIP to manual injection from MOSPI's monthly release.
-- The source_series_id is preserved for historical reference.

UPDATE indicators
SET data_source = 'manual',
    updated_at = NOW()
WHERE code = 'IND_NIFTY_05_IIP';

-- ── D2b (confirmed by the user 2026-09-13): India CPI is hand-filled; seed.ts says fred 
UPDATE indicators
SET data_source = 'manual',
    updated_at = NOW()
WHERE code = 'IND_NIFTY_03_CPI';

-- ── 20260629120000_recalibrate_nifty_ind13_fii_ls_bands ───────────────────
-- Recalibrate NIFTY Ind 13 (IND_NIFTY_13_FII_LS_RATIO) scoring bands.
--
-- The stored value is a long-SHARE percentage on a 0-100 scale:
--   long_pct = FII Future Index Long / (Long + Short) * 100
-- (NOT a raw long/short ratio, NOT a 0-1 fraction). The threshold_bands handler
-- treats band.min as inclusive (>=) and band.max as exclusive (<).
--
-- OLD bands (45/55):                NEW bands (50/28.6):
--   >= 55        -> +1               >= 50        -> +1   (ratio > 1.0)
--   45 <= x < 55 ->  0               28.6 <= x < 50 ->  0 (ratio 0.4 .. 1.0)
--   x < 45       -> -1               x < 28.6     -> -1   (ratio < 0.4)
--
-- Recalibrated from 45/55 (which assumed a 50%-balanced center). FII index-futures
-- long share is structurally skewed toward shorts (FIIs hedge cash longs with
-- futures shorts), so it sits below 45% in essentially all regimes and the old
-- bands pinned Ind 13 permanently at -1 (dead signal). New bands center the neutral
-- zone on the metric's real operating range. Reference: historical FII long/short
-- ratio 0.15 (Dec 2024 bearish extreme) to 5+ (strong-bull extreme); crossover to
-- net-long = ratio 1.0 = 50% share. 50/28.6 thresholds derive from ratio 1.0 and
-- 0.4 — not fit to current data.
--
-- This only changes the current regime's signal during FUTURE bull phases
-- (share > 28.6% / ratio > 0.4). Today's bearish readings (~13% share) remain -1.
-- Single-indicator change: scoped by indicator code; no other indicator touched.
-- Updates ONLY the 'bands' key of rule_definition (jsonb_set), preserving metric,
-- cadence, live_tracking_only and historical_default.
UPDATE "scoring_rules"
SET "rule_definition" = jsonb_set(
  "rule_definition"::jsonb,
  '{bands}',
  '[
    { "min": 50.0, "max": null, "score": 1 },
    { "min": 28.6, "max": 50.0, "score": 0 },
    { "min": null, "max": 28.6, "score": -1 }
  ]'::jsonb
)
WHERE "indicator_id" = (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_13_FII_LS_RATIO')
  AND "version" = 2;

-- ── 20260702120100_fix_nifty_ind7_dii_absorption_net_formula ──────────────
-- Fix NIFTY Ind 7 (IND_NIFTY_07_DII_ABSORPTION) scoring: net numerator + new tiers.
--
-- The absorption numerator was DII GROSS buy; it must be DII NET (buy − sell). The
-- ingestion service now computes ratio = dii_net / abs(fii_sell) using NSE's own
-- precomputed net field. This migration realigns the LIVE v2 scoring rule's tier
-- table and formula doc string to match. (seed-rules-v2.ts uses upsert update:{} and
-- will NOT touch a live DB, so the live rule must be patched here — same pattern as
-- 20260629120000_recalibrate_nifty_ind13_fii_ls_bands.)
--
-- The rolling_ratio_excluding handler treats tier.min as inclusive (>=) and tier.max
-- as exclusive (<).
--
-- OLD tiers (gross-buy ratio):        NEW tiers (net ratio):
--   >= 0.75         -> +1              >= 0.75        -> +1
--   0.5 <= x < 0.75 ->  0              0 <= x < 0.75  ->  0
--   x < 0.5         -> -1              x < 0          -> -2   ("both fleeing")
--
-- The -2 tier (DII also net selling on the FII-seller days) is NEW; the boundary at 0
-- is NEW; the old 0.5 cutpoint is REMOVED. When the rolling average is < 0 the handler
-- also emits the flag 'DII_NET_SELLER_REGIME'.
--
-- Scoped by indicator code and version; no other indicator or rule version touched.
-- Updates ONLY the 'tiers' and 'formula' keys, preserving lookback_trading_days,
-- exclusion, all_excluded_fallback and cadence.
--
-- FORWARD-ONLY: existing historical data_points rows are NOT modified or recomputed.
-- Only the scoring rule that future score computations use is changed.
UPDATE "scoring_rules"
SET "rule_definition" = jsonb_set(
  jsonb_set(
    "rule_definition"::jsonb,
    '{tiers}',
    '[
      { "min": 0.75, "max": null, "score": 1 },
      { "min": 0, "max": 0.75, "score": 0 },
      { "min": null, "max": 0, "score": -2 }
    ]'::jsonb
  ),
  '{formula}',
  '"dii_net / abs(fii_sell)"'::jsonb,
  true
)
WHERE "indicator_id" = (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_07_DII_ABSORPTION')
  AND "version" = 2;

-- ── 20260817130000_nifty_ind13_percentile_rank_v3 ─────────────────────────
-- Replace IND_NIFTY_13_FII_LS_RATIO scoring: threshold_bands (static 28.6/50
-- long_pct bands) -> percentile_rank (expanding-window percentile of long_pct
-- against its own history).
--
-- This is a NEW version row (v3), not an in-place edit of v2's rule_definition.
-- The 2026-06-29 recalibration migration mutated v2's bands via jsonb_set,
-- which destroyed the ability to see what the rule looked like before that
-- change. Versioning it properly this time: v2 is closed out with
-- effective_to = yesterday, v3 opens at effective_from = today. v2's row and
-- its (already-anomalous, pre-existing, NOT touched here) effective_from value
-- are otherwise left exactly as they were.
--
-- New rule (handlers/percentile-rank.handler.ts):
--   * min_observations: 60 (expanding-window count as of the scoring date,
--     inclusive of that date's own reading). Below 60 -> score 0, flagged
--     INSUFFICIENT_HISTORY, no -1/+1 ever emitted on a short window.
--   * bands are percentile tiers, same min-inclusive/max-exclusive convention
--     as every other banded rule in this codebase:
--       percentile <  20            -> -1
--       20 <= percentile < 80       ->  0
--       percentile >= 80            -> +1
--   * contrarian_watch_max_percentile: 5 -- when percentile < 5 (a subset of
--     the -1 tier), additionally sets flag CONTRARIAN_WATCH, same mechanism
--     VIX's band_with_flag rule already uses (flag on a Band, surfaced via
--     Score.flag -> indicator_breakdown -> public API `flags` array).
--   * historical_default: 0 -- if no data point exists at all for/before the
--     scoring date (e.g. pre-2026-05-04), same HISTORICAL_DEFAULT_NO_DATA
--     fallback the old rule used, unchanged behaviour.
--   * Percentile is computed against DISTINCT observation dates, not raw
--     data_points rows -- 2026-07-16 has two is_current rows (a pre-existing,
--     out-of-scope data anomaly); the handler collapses same-date rows to the
--     most recent vintage_date before ranking.
--
-- As of this migration, IND_NIFTY_13_FII_LS_RATIO has 55 distinct dated
-- observations (2026-05-04 .. 2026-08-14) -- below the 60-observation floor,
-- so every date scores 0 / INSUFFICIENT_HISTORY until 5 more trading days of
-- data have been ingested. This is expected, not a bug -- see chat report.
UPDATE "scoring_rules"
SET "effective_to" = '2026-08-16'
WHERE "indicator_id" = (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_13_FII_LS_RATIO')
  AND "version" = 2
  AND "effective_to" IS NULL;

INSERT INTO "scoring_rules" (
  "id",
  "indicator_id",
  "version",
  "rule_type",
  "rule_definition",
  "effective_from",
  "effective_to",
  "notes",
  "created_at"
)
VALUES (
  gen_random_uuid()::text,
  (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_13_FII_LS_RATIO'),
  3,
  'custom',
  '{
    "type": "percentile_rank",
    "metric": "long_pct",
    "window": "expanding",
    "min_observations": 60,
    "bands": [
      { "min": null, "max": 20, "score": -1 },
      { "min": 20, "max": 80, "score": 0 },
      { "min": 80, "max": null, "score": 1 }
    ],
    "contrarian_watch_max_percentile": 5,
    "contrarian_watch_flag": "CONTRARIAN_WATCH",
    "historical_default": 0,
    "cadence": "daily"
  }'::jsonb,
  '2026-08-17',
  NULL,
  'v3: replaces static threshold_bands (28.6/50 on long_pct) with an expanding-window percentile rank. Ind 13 is excluded from net_score as of this same date (see nifty_scorecards.ind_13_score migration) pending validation.',
  CURRENT_TIMESTAMP
)
ON CONFLICT ("indicator_id", "version") DO NOTHING;

-- ── 20260817150000_nifty_ind10_11_12_slope_sigma_v3 ───────────────────────
-- Replace the price-block indicators' scoring: endpoint-delta
-- (rolling_pct_direction / rolling_pct_tiered, comparing only the newest and
-- oldest of an 11-row window) -> rolling_slope_sigma (an OLS fit across all
-- 10 observations in the window, scored against the indicator's own trailing
-- volatility instead of a fixed percentage).
--
--   Ind 10 IND_NIFTY_10_DXY     3-tier, +/-0.5 sigma
--   Ind 11 IND_NIFTY_11_BRENT   3-tier, +/-0.5 sigma (same tier shape as DXY)
--   Ind 12 IND_NIFTY_12_USDINR  5-tier, +/-0.5 / +/-1.5 sigma (unchanged tier
--                               count from the old rule; boundaries changed
--                               from fixed pct to sigma multiples)
--
-- Handler: handlers/rolling-slope-sigma.handler.ts (new, registered as
-- rolling_slope_sigma in engine.ts). Not shared with rolling_pct_direction /
-- rolling_pct_tiered, which remain registered and unchanged -- their v2 rows
-- close out below but stay fully functional for any future rescoring of a
-- date that falls in their effective range (2020-01-01 .. 2026-08-16).
--
-- window_size: 10 (NOT 11 -- correction from Phase A recon, which found the
-- old handlers' `needed = lookback_trading_days + 1 = 11` produces a 2-point
-- endpoint delta across an 11-row set; the OLS fit specified for this rule
-- uses all 10 observations directly, x = 0..9, so the window requirement is
-- 10, not 11).
--
-- sigma_lookback_max: 250, sigma_lookback_min: 60 (below 60 -> insufficient_data).
--
-- Known, documented, accepted limitation for Ind 10 (DXY): ingestion for this
-- indicator only began 2026-04-23, so as of this migration DXY has ~82
-- distinct dated observations (~73 possible slope-measure points) -- it will
-- not reach the 250-observation sigma target until roughly April 2027 at
-- daily cadence. Per instruction, DXY runs the IDENTICAL algorithm as Brent
-- and USD/INR with no special-casing and no compensating rule: sigma is a
-- volatility estimate rather than a signal estimate, and is reasonably
-- stable at n~=75; the fixed-percentage rule it replaces was calibrated on no
-- data at all, so a volatility-derived deadband from ~75 observations is
-- still a strict improvement.
--
-- This migration touches ONLY scoring_rules. Per instruction, NO historical
-- nifty_scorecards row is backfilled or rescored in this phase -- existing
-- scores keep whatever the v2 endpoint-delta rule produced for their date.
-- The new v3 rule applies live-forward only, starting today.
UPDATE "scoring_rules"
SET "effective_to" = '2026-08-16'
WHERE "indicator_id" IN (
  SELECT "id" FROM "indicators"
  WHERE "code" IN ('IND_NIFTY_10_DXY', 'IND_NIFTY_11_BRENT', 'IND_NIFTY_12_USDINR')
)
AND "version" = 2
AND "effective_to" IS NULL;

INSERT INTO "scoring_rules" (
  "id", "indicator_id", "version", "rule_type", "rule_definition",
  "effective_from", "effective_to", "notes", "created_at"
)
VALUES
(
  gen_random_uuid()::text,
  (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_10_DXY'),
  3,
  'custom',
  '{
    "type": "rolling_slope_sigma",
    "window_size": 10,
    "sigma_lookback_max": 250,
    "sigma_lookback_min": 60,
    "bands": [
      { "min": null, "max": -0.5, "score": 1 },
      { "min": -0.5, "max": 0.5,  "score": 0 },
      { "min": 0.5,  "max": null, "score": -1 }
    ],
    "cadence": "daily"
  }'::jsonb,
  '2026-08-17',
  NULL,
  'v3: OLS slope over the 10-observation window, scored against trailing sigma (min 60, target 250 observations) instead of a fixed pct threshold. Known limitation: DXY has only ~82 distinct observations as of this rule (ingestion began 2026-04-23) -- sigma runs on a shorter window than Brent/USDINR until ~April 2027, by design, no special-casing.',
  CURRENT_TIMESTAMP
),
(
  gen_random_uuid()::text,
  (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_11_BRENT'),
  3,
  'custom',
  '{
    "type": "rolling_slope_sigma",
    "window_size": 10,
    "sigma_lookback_max": 250,
    "sigma_lookback_min": 60,
    "bands": [
      { "min": null, "max": -0.5, "score": 1 },
      { "min": -0.5, "max": 0.5,  "score": 0 },
      { "min": 0.5,  "max": null, "score": -1 }
    ],
    "cadence": "daily"
  }'::jsonb,
  '2026-08-17',
  NULL,
  'v3: OLS slope over the 10-observation window, scored against trailing sigma (min 60, target 250 observations) instead of a fixed pct threshold.',
  CURRENT_TIMESTAMP
),
(
  gen_random_uuid()::text,
  (SELECT "id" FROM "indicators" WHERE "code" = 'IND_NIFTY_12_USDINR'),
  3,
  'custom',
  '{
    "type": "rolling_slope_sigma",
    "window_size": 10,
    "sigma_lookback_max": 250,
    "sigma_lookback_min": 60,
    "bands": [
      { "min": null, "max": -1.5, "score": 2 },
      { "min": -1.5, "max": -0.5, "score": 1 },
      { "min": -0.5, "max": 0.5,  "score": 0 },
      { "min": 0.5,  "max": 1.5,  "score": -1 },
      { "min": 1.5,  "max": null, "score": -2 }
    ],
    "cadence": "daily"
  }'::jsonb,
  '2026-08-17',
  NULL,
  'v3: OLS slope over the 10-observation window, scored against trailing sigma (min 60, target 250 observations) instead of a fixed pct threshold. 5-tier resolution unchanged from v2.',
  CURRENT_TIMESTAMP
)
ON CONFLICT ("indicator_id", "version") DO NOTHING;

-- ── 20260817160000_nse_holiday_calendar (INSERT only; the table is built by db push) 
INSERT INTO "nse_holidays" ("date", "name") VALUES
-- 2022
('2022-01-26', 'Republic Day'),
('2022-03-01', 'Maha Shivaratri'),
('2022-04-10', 'Ram Navami'),
('2022-04-14', 'Dr. Baba Saheb Ambedkar Jayanti'),
('2022-04-15', 'Good Friday'),
('2022-05-03', 'Id-ul-Fitr (Ramzan Id)'),
('2022-07-10', 'Bakri Id / Eid ul-Adha'),
('2022-08-09', 'Muharram'),
('2022-08-31', 'Ganesh Chaturthi'),
('2022-10-02', 'Mahatma Gandhi Jayanti'),
('2022-10-05', 'Dasara'),
('2022-10-24', 'Diwali-Laxmi Pujan / Diwali-Balipratipada'),
('2022-11-08', 'Guru Nanak Jayanti'),
('2022-12-25', 'Christmas'),
-- 2023
('2023-01-26', 'Republic Day'),
('2023-03-07', 'Holi'),
('2023-03-30', 'Ram Navami'),
('2023-04-04', 'Mahavir Jayanti'),
('2023-04-07', 'Good Friday'),
('2023-04-14', 'Dr. Baba Saheb Ambedkar Jayanti'),
('2023-04-21', 'Id-ul-Fitr (Ramzan Id)'),
('2023-05-01', 'Maharashtra Day'),
('2023-06-28', 'Bakri Id / Eid ul-Adha'),
('2023-08-15', 'Independence Day'),
('2023-09-19', 'Ganesh Chaturthi'),
('2023-10-02', 'Mahatma Gandhi Jayanti'),
('2023-10-24', 'Dasara'),
('2023-11-12', 'Diwali-Laxmi Pujan'),
('2023-11-14', 'Diwali-Balipratipada'),
('2023-11-27', 'Guru Nanak Jayanti'),
('2023-12-25', 'Christmas'),
-- 2024
('2024-01-26', 'Republic Day'),
('2024-03-08', 'Maha Shivaratri'),
('2024-03-25', 'Holi'),
('2024-03-29', 'Good Friday'),
('2024-04-10', 'Id-ul-Fitr (Ramzan Id)'),
('2024-04-14', 'Dr. Baba Saheb Ambedkar Jayanti'),
('2024-04-17', 'Ram Navami'),
('2024-04-21', 'Mahavir Jayanti'),
('2024-05-01', 'Maharashtra Day'),
('2024-06-17', 'Bakri Id / Eid ul-Adha'),
('2024-07-17', 'Muharram'),
('2024-08-15', 'Independence Day'),
('2024-09-07', 'Ganesh Chaturthi'),
('2024-10-02', 'Mahatma Gandhi Jayanti'),
('2024-10-13', 'Dasara'),
('2024-11-01', 'Diwali-Laxmi Pujan'),
('2024-11-02', 'Diwali-Balipratipada'),
('2024-11-15', 'Guru Nanak Jayanti'),
('2024-12-25', 'Christmas'),
-- 2025
('2025-01-26', 'Republic Day'),
('2025-02-26', 'Maha Shivaratri'),
('2025-03-14', 'Holi'),
('2025-03-31', 'Id-ul-Fitr (Ramzan Id)'),
('2025-04-06', 'Ram Navami'),
('2025-04-10', 'Mahavir Jayanti'),
('2025-04-14', 'Dr. Baba Saheb Ambedkar Jayanti'),
('2025-04-18', 'Good Friday'),
('2025-05-01', 'Maharashtra Day'),
('2025-06-07', 'Bakri Id / Eid ul-Adha'),
('2025-07-06', 'Muharram'),
('2025-08-15', 'Independence Day'),
('2025-08-27', 'Ganesh Chaturthi'),
('2025-10-02', 'Dasara / Mahatma Gandhi Jayanti'),
('2025-10-21', 'Diwali-Laxmi Pujan (Morning Off)'),
('2025-10-22', 'Diwali-Balipratipada'),
('2025-11-05', 'Guru Nanak Jayanti'),
('2025-12-25', 'Christmas'),
-- 2026
('2026-01-26', 'Republic Day'),
('2026-03-03', 'Holi'),
('2026-03-26', 'Ram Navami'),
('2026-03-31', 'Mahavir Jayanti'),
('2026-04-03', 'Good Friday'),
('2026-04-14', 'Dr. Baba Saheb Ambedkar Jayanti'),
('2026-05-01', 'Maharashtra Day'),
('2026-05-28', 'Bakri Id / Eid ul-Adha'),
('2026-06-26', 'Muharram'),
('2026-09-14', 'Ganesh Chaturthi'),
('2026-10-02', 'Mahatma Gandhi Jayanti'),
('2026-10-20', 'Dasara'),
('2026-11-08', 'Diwali-Laxmi Pujan (Morning Off)'),
('2026-11-10', 'Diwali-Balipratipada'),
('2026-11-24', 'Guru Nanak Jayanti'),
('2026-12-25', 'Christmas')
ON CONFLICT ("date") DO NOTHING;

COMMIT;
